# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-17 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def order_to_orderline(apps, schema_editor):
    reviews_model = apps.get_model("shuup_product_reviews", "ProductReview")
    order_line_model = apps.get_model("shuup", "OrderLine")
    for review in reviews_model.objects.all():
        # Here the first priority is working database. Maybe someone break
        # the rules and the reviews are linked to orders which does not
        # actually include the reviewed product. Fallback to first line
        # of that order.
        order_line = order_line_model.objects.filter(order=review.order, product=review.product).first()
        if not order_line:
            order_line = order_line_model.objects.filter(order=review.order).first()

        review.order_line = order_line
        review.save()


def orderline_to_order(apps, schema_editor):
    reviews_model = apps.get_model("shuup_product_reviews", "ProductReview")
    for review in reviews_model.objects.all():
        if reviews_model.objects.filter(reviewer=review.reviewer, product=review.product).count() > 1:
            review.delete()  # reviewer and product needs to be unique together
        else:
            review.order = review.order_line.order
            review.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shuup', '0057_remove_product_stock_behavior'),
        ('shuup_product_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='shuup.OrderLine', verbose_name='order line'),
        ),
        migrations.AlterUniqueTogether(
           name='productreview',
           unique_together=set([]),
        ),
        migrations.RunPython(order_to_orderline, reverse_code=orderline_to_order),
        migrations.RemoveField(
            model_name='productreview',
            name='order',
        ),
    ]
