# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-17 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_product_reviews', '0002_make_order_order_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='shuup.OrderLine', verbose_name='order line'),
        ),
    ]
